
on:
    push: 
name: action
jobs:
    hello-wordl:
        name: Job para saludar
        runs-on: ubuntu-22.04
        steps:
            - name: Step Hola Mundo
              id: hello
              uses: AlvaroEng98/docker-hello-world@v1
              with:
                  who-to: "Avalor"
            - name: Usar Output
              run: echo "Fecha es ${{ steps.hello.outputs.time }}"