name: hello

on:
  push:
    branches: ["develop"]

  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

